CANBOOKRAM/Controllers/FollowersController.cs
using CANBOOKRAM.Data;
using CANBOOKRAM.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CANBOOKRAM.Controllers
{
    public class FollowersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FollowersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {

            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            var followers = _context.UserFriends.Include("User").Where(i => i.Friend == applicationUser).ToList();
            return View(followers);
        }

        public async Task<IActionResult> RefreshList()
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            var followers = _context.UserFriends.Include("User").Where(i => i.Friend == applicationUser).ToList();

            return PartialView("_FollowersPartial", followers);
        }

        [HttpPost]
        public IActionResult RemoveFollower(int id)
        {
            var relation = _context.UserFriends.Where(i => i.Id == id).FirstOrDefault();

            if (relation != null)
            {
                _context.UserFriends.Remove(relation);
                _context.SaveChanges();

                return Ok();
            }
            else
            {
                return BadRequest(new { message = "Relation not found" });
            }
        }
    }
}

CANBOOKRAM/Controllers/FollowingController.cs
using CANBOOKRAM.Data;
using CANBOOKRAM.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CANBOOKRAM.Controllers
{
    public class FollowingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FollowingController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {

            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            var following = _context.UserFriends.Include("Friend").Where(i => i.User == applicationUser).ToList();
            return View(following);
        }

        public async Task<IActionResult> RefreshList()
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            var following = _context.UserFriends.Include("Friend").Where(i => i.User == applicationUser).ToList();

            return PartialView("_FollowingPartial", following);
        }

        [HttpPost]
        public IActionResult RemoveFollowing(int id)
        {
            var relation = _context.UserFriends.Where(i => i.Id == id).FirstOrDefault();

            if (relation != null)
            {
                _context.UserFriends.Remove(relation);
                _context.SaveChanges();

                return Ok();
            }
            else
            {
                return BadRequest(new { message = "Relation not found" });
            }
        }
    }
}

CANBOOKRAM/Controllers/ProfileController.cs
using CANBOOKRAM.Data;
using CANBOOKRAM.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CANBOOKRAM.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProfileController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string id)
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);

            var follwers = from i in _context.UserFriends where i.Friend.Id == id select i;
            var following = (from i in _context.UserFriends where i.User == applicationUser && i.Friend.Id == id select i).FirstOrDefault();
            var rates = (from i in _context.UserRatings where i.User.Id == id select i.Rate).ToList();
            var rated = (from i in _context.UserRatings where i.User.Id == id && i.WhoRated.Id == applicationUser.Id select i).FirstOrDefault();

            var user = (from i in _context.Users
                        where i.Id == id
                        select new UserModel
                        {
                            UserId = i.Id,
                            Name = i.Name,
                            Email = i.Email,
                            UserName = i.UserName,
                            PhoneNumber = i.PhoneNumber,
                            ProfilePicture = i.ProfilePicture,
                            BirthDate = i.BirthDate,
                            Gender = i.Gender,
                            City = i.City,
                            IsPrivate = i.IsPrivate,
                            FollowerCount = follwers.Count(),
                            IsFollowing = following != null ? true : false,
                            RelationId = following != null ? following.Id : 0,
                            IsRated = rated != null ? true : false,
                            YourRate = rated != null ? rated.Rate : 0
                        }).FirstOrDefault();

            if (user != null)
            {
                user.AvgRating = CalculateRate.GetRating(rates);

                if (!user.IsPrivate || user.UserId == applicationUser.Id || user.IsFollowing)
                {
                    var posts = (from i in _context.UserPosts.Include("User").Include("Likes") where i.User.Id == id orderby i.TimeStamp descending select i).ToList();
                    user.UserPosts = posts;

                    var top = (from i in _context.UserPosts.Include("User").Include("Likes") where i.User.Id == id orderby i.Likes.Count descending select i).ToList();
                    user.TopPosts = top.Take(5).ToList();
                }
            }

            return View(user);
        }

        public async Task<IActionResult> RefreshPosts(string userId)
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            var user = (from i in _context.Users where i.Id == userId select i).FirstOrDefault();
            var following = (from i in _context.UserFriends where i.User == applicationUser && i.Friend.Id == userId select i).FirstOrDefault();

            if (!user.IsPrivate || user.Id == applicationUser.Id || following != null)
            {
                var posts = (from i in _context.UserPosts.Include("User").Include("Likes") where i.User.Id == userId orderby i.TimeStamp descending select i).ToList();
                return PartialView("_PostListPartial", posts);
            }
            else
            {
                return PartialView("_PostListPartial", null);
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddRating(string userId, int rate)
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            var user = (from i in _context.Users where i.Id == userId select i).FirstOrDefault();

            if (user != null)
            {
                var model = (from i in _context.UserRatings where i.User == user && i.WhoRated == applicationUser select i).FirstOrDefault();

                if (model != null)
                {
                    model.Rate = rate;
                    model.DateTime = DateTime.Now;
                } 
                else
                {
                    model = new UserRating();
                    model.User = user;
                    model.WhoRated = applicationUser;
                    model.Rate = rate;
                    model.DateTime = DateTime.Now;

                    _context.UserRatings.Add(model);
                }

                _context.SaveChanges();

                return Ok();
            }
            else
            {
                return BadRequest(new { message = "User not found" });
            }
        }

        [HttpPost]
        public async Task<IActionResult> RemoveRating(string userId)
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            var rating = (from i in _context.UserRatings where i.User.Id == userId && i.WhoRated == applicationUser select i).FirstOrDefault();

            if (rating != null)
            {
                _context.UserRatings.Remove(rating);
                _context.SaveChanges();

                return Ok();
            }
            else
            {
                return BadRequest(new { message = "Rating not found" });
            }
        }
    }
}

CANBOOKRAM/Views/Shared/_FollowersPartial.cshtml
@model List<UserFriend>

@foreach(var item in Model)
{
    <div class="d-md-flex align-items-center mb-4">
        <!-- Avatar -->
        <div class="avatar me-3 mb-3 mb-md-0">
            @if (item.User.ProfilePicture == null)
            {
                <img class="avatar-img rounded-circle" src="/assets/images/pp.png" alt="">
            }
            else
            {
                <img class="avatar-img rounded-circle" src="data:image/*;base64,@(Convert.ToBase64String(item.User.ProfilePicture))" alt="">
            }
        </div>
        <!-- Info -->
        <div class="w-100">
        <div class="d-sm-flex align-items-start">
            <h6 class="mb-0"><a asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@item.User.Id">@(!String.IsNullOrEmpty(item.User.Name) ? item.User.Name : item.User.UserName) </a></h6>
            <p class="small ms-sm-2 mb-0">Full Stack Web Developer</p>
        </div>
        <!-- Connections START -->
        <ul class="avatar-group mt-1 list-unstyled align-items-sm-center">
            <li class="small">
            Joan Wallace and Larry Lawson shared connections
            </li>
        </ul>
        <!-- Connections END -->
        </div>
        <!-- Button -->
        <div class="ms-md-auto d-flex">
        <button class="btn btn-danger-soft btn-sm mb-0 me-2" onclick="RemoveFollower('@item.Id')"> Remove Follower </button>
        </div>
    </div>
}

CANBOOKRAM/Views/Shared/_FollowingPartial.cshtml
@model List<UserFriend>

@foreach(var item in Model)
{
    <div class="d-md-flex align-items-center mb-4">
        <!-- Avatar -->
        <div class="avatar me-3 mb-3 mb-md-0">
            @if (item.Friend.ProfilePicture == null)
            {
                <img class="avatar-img rounded-circle" src="/assets/images/pp.png" alt="">
            }
            else
            {
                <img class="avatar-img rounded-circle" src="data:image/*;base64,@(Convert.ToBase64String(item.Friend.ProfilePicture))" alt="">
            }
        </div>
        <!-- Info -->
        <div class="w-100">
        <div class="d-sm-flex align-items-start">
            <h6 class="mb-0"><a asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@item.Friend.Id">@(!String.IsNullOrEmpty(item.Friend.Name) ? item.Friend.Name : item.Friend.UserName) </a></h6>
            <p class="small ms-sm-2 mb-0">Full Stack Web Developer</p>
        </div>
        <!-- Connections START -->
        <ul class="avatar-group mt-1 list-unstyled align-items-sm-center">
            <li class="small">
            Joan Wallace and Larry Lawson shared connections
            </li>
        </ul>
        <!-- Connections END -->
        </div>
        <!-- Button -->
        <div class="ms-md-auto d-flex">
        <button class="btn btn-danger-soft btn-sm mb-0 me-2" onclick="RemoveFollowing('@item.Id')"> Remove </button>
        </div>
    </div>
}

CANBOOKRAM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CANBOOKRAM</title>

    <!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap">

    <link rel="stylesheet" type="text/css" href="~/theme/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/theme/css/style.css" />
</head>
<body>
    <header class="navbar-light fixed-top header-static bg-mode">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="light-mode-item navbar-brand-item" src="~/assets/images/logo.png" alt="logo">
				<img class="dark-mode-item navbar-brand-item" src="~/assets/images/logo.png" alt="logo">
                </a>

                <button class="navbar-toggler ms-auto icon-md btn btn-light p-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-animation">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </button>


      <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="nav mt-3 mt-lg-0 flex-nowrap align-items-center px-4 px-lg-0">
          <div class="nav-item w-100">
            <form class="rounded position-relative">
              <input class="form-control ps-5 bg-light" type="search" placeholder="Search..." aria-label="Search">
              <button class="btn bg-transparent px-2 py-0 position-absolute top-50 start-0 translate-middle-y" type="submit"><i class="fa-light fa-magnifying-glass fs-5"> </i></button>
            </form>
          </div>
        </div>

        <div></div>
      </div>
      <ul class="nav flex-nowrap align-items-center ms-sm-3 list-unstyled">
        <partial name="_LoginPartial" />
        </ul>
    </div>
    </nav>
    </header>
    <main>
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CANBOOKRAM/Views/Shared/_PostListPartial.cshtml
@model List<UserPost>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@foreach (var item in Model)
{
    var youLike = item.Likes.Where(i => i.User == UserManager.GetUserAsync(User).Result).FirstOrDefault();

    <div class="card mb-4">
        <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between">
              <div class="d-flex align-items-center">
                <!-- Avatar -->
                <a class="avatar avatar-story me-2" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@item.User.Id">
                @if (item.User.ProfilePicture == null)
                {
                    <img class="avatar-img rounded-circle" src="/assets/images/pp.png" alt="">
                }
                else
                {
                    <img class="avatar-img rounded-circle" src="data:image/*;base64,@(Convert.ToBase64String(item.User.ProfilePicture))" alt="">
                }
                </a>
                <!-- Info -->
                <div>
                  <div class="nav nav-divider">
                    <a asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@item.User.Id"><h6 class="nav-item card-title mb-0 me-2"> @item.User.UserName </h6></a>
                    <span class="nav-item small"> @item.TimeStamp.ToString("dd MMM, HH:mm")</span>
                  </div>
                  <p class="mb-0 small">Web Developer</p>
                </div>
              </div>
              <!-- Card feed action dropdown START -->
              <div class="dropdown">
                <a href="#" class="text-secondary btn btn-secondary-soft-hover py-1 px-2" id="cardFeedAction" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="far fa-ellipsis-h"></i>
                </a>
                <!-- Card feed action dropdown menu -->
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="cardFeedAction">
                  <li><a class="dropdown-item" href="#"> <i class="far fa-bookmark fa-fw pe-2"></i>Save post</a></li>
                    @if(item.User != UserManager.GetUserAsync(User).Result)
                    {
                        <li><a class="dropdown-item" href="#"> <i class="far fa-user-times fa-fw pe-2"></i>Unfollow @item.User.UserName </a></li>
                    }
                        
                    @if(item.User == UserManager.GetUserAsync(User).Result)
                    {
                       <li><hr class="dropdown-divider"></li>
                       <li><span class="dropdown-item" onclick="DeletePost('@item.Id')" style="cursor:pointer"> <i class="far fa-trash-alt fa-fw pe-2"></i>Delete post</span></li>
                    }
                </ul>
              </div>
              <!-- Card feed action dropdown END -->
            </div>
          </div>
          <div class="card-body">
             <p>@item.Message</p>
            @if (item.Image != null)
            {
                <img class="card-img" src="data:image/*;base64,@(Convert.ToBase64String(item.Image))" alt="Post">
            }
            <ul class="nav nav-stack pt-3 small">
                <li class="nav-item">
                    @if (youLike != null)
                    {
                        <span class="nav-link active" onclick="LikePost('@item.Id')" style="cursor:pointer"> <i class="fas fa-thumbs-up pe-1"></i>Liked (@item.Likes.Count)</span>
                    }
                    else
                    {
                        <span class="nav-link" onclick="LikePost('@item.Id')" style="cursor:pointer"> <i class="far fa-thumbs-up pe-1"></i>Liked (@item.Likes.Count)</span>
                    }
                </li>
             </ul>
          </div>
    </div>
} 

CANBOOKRAM/Views/Shared/_PostPartial.cshtml
@model UserPost
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<div class="card">
    <form data-ajax="true" data-ajax-method="POST" data-ajax-failure="OnFailure"
            data-ajax-success="OnSuccess" asp-controller="Home" asp-action="CreatePost" class="card-body" enctype="multipart/form-data">
        <div class="d-flex mb-3">
            <div class="avatar avatar-xs me-2">
                @if (UserManager.GetUserAsync(User).Result.ProfilePicture != null)
                {
                    <img class="avatar-img rounded-circle" src="data:image/*;base64,@(Convert.ToBase64String(UserManager.GetUserAsync(User).Result.ProfilePicture))" alt="avatar">
                }
                else
                {
                    <img class="avatar-img rounded-circle" src="/assets/images/pp.png" alt="">
                }
            </div>
            <div class="w-100">
                <textarea asp-for="Message" class="form-control pe-4 border-0" rows="2" data-autoresize="" placeholder="Share your thoughts..." style="height: 80px;"></textarea>
            </div>
        </div>
        <ul class="nav nav-pills nav-stack small fw-normal">
            <li class="nav-item">
                <input type="file" accept=".png,.jpg,.jpeg"
                       asp-for="Image"
                       class="nav-link bg-light py-1 px-2 mb-0" />
            </li>
            <li class="nav-item dropdown ms-sm-auto">
                <button type="submit" class="nav-link bg-light py-1 px-2 mb-0">
                    Submit
                </button>
            </li>
        </ul>
    </form>
</div>
<script>
    function OnFailure() {
       alert("An error occured");
    }
 
    function OnSuccess() {
        $("#Message").val('');
        $("#Image").val(null);
        RefreshPostList();
    }
</script>

CANBOOKRAM/Views/Shared/_RequestsPartial.cshtml
@model List<FriendRequest>

@foreach(var item in Model)
{
    <div class="d-md-flex align-items-center mb-4">
        <!-- Avatar -->
        <div class="avatar me-3 mb-3 mb-md-0">
            @if (item.User.ProfilePicture == null)
            {
                <img class="avatar-img rounded-circle" src="/assets/images/pp.png" alt="">
            }
            else
            {
                <img class="avatar-img rounded-circle" src="data:image/*;base64,@(Convert.ToBase64String(item.User.ProfilePicture))" alt="">
            }
        </div>
        <!-- Info -->
        <div class="w-100">
        <div class="d-sm-flex align-items-start">
            <h6 class="mb-0"><a asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@item.User.Id">@(!String.IsNullOrEmpty(item.User.Name) ? item.User.Name : item.User.UserName) </a></h6>
            <p class="small ms-sm-2 mb-0">Full Stack Web Developer</p>
        </div>
        <!-- Connections START -->
        <ul class="avatar-group mt-1 list-unstyled align-items-sm-center">
            <li class="small">
            Joan Wallace and Larry Lawson shared connections
            </li>
        </ul>
        <!-- Connections END -->
        </div>
        <!-- Button -->
        <div class="ms-md-auto d-flex">
        <button class="btn btn-danger-soft btn-sm mb-0 me-2" onclick="RemoveRequest('@item.Id')"> Remove </button>
        <button class="btn btn-primary-soft btn-sm mb-0" onclick="AcceptRequest('@item.Id')"> Accept </button>
        </div>
    </div>
}

CANBOOKRAM/Views/Shared/_TrendingPostsPartial.cshtml
@model List<UserPost>

<div class="col-sm-6 col-lg-12">
    <div class="card">
        <!-- Card header START -->
        <div class="card-header pb-0 border-0">
            <h5 class="card-title mb-0">Trending Posts</h5>
        </div>
        <!-- Card header END -->
        <!-- Card body START -->
        <div class="card-body">
            @foreach(var item in Model)
            {
                <div class="mb-3">
                    <h6 class="mb-0 post-text"><a asp-area="" asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">@item.Message</a></h6>
                    <small>@item.TimeStamp.ToString("dd MMM, HH:mm")</small>
                </div>
            }
        </div>
        <!-- Card body END -->
    </div>
    </div>

CANBOOKRAM/Views/Shared/_UserSidebarPartial.cshtml
@model HomeModel
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager

@{
    var _user = UserManager.GetUserAsync(User).Result;
}

<nav class="navbar navbar-expand-lg mx-0"> 
          <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasSideNavbar">
            <!-- Offcanvas header -->
            <div class="offcanvas-header">
              <button type="button" class="btn-close text-reset ms-auto" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>

            <!-- Offcanvas body -->
            <div class="offcanvas-body d-block px-2 px-lg-0">
              <!-- Card START -->
              <div class="card overflow-hidden">
                <!-- Cover image -->
                <div class="h-50px" style="background-image:url(assets/images/bg/01.jpg); background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
                  <!-- Card body START -->
                  <div class="card-body pt-0">
                    <div class="text-center">
                    <!-- Avatar -->
                    <div class="avatar avatar-lg mt-n5 mb-3">
                        @if (_user.ProfilePicture != null)
                        {
                            <img class="avatar-img rounded border border-white border-3" src="data:image/*;base64,@(Convert.ToBase64String(_user.ProfilePicture))" alt="">
                        }
                        else
                        {
                            <img class="avatar-img rounded border border-white border-3" src="/assets/images/pp.png" alt="">
                        }
                    </div>
                    <!-- Info -->
                    <h5 class="mb-0"> <a asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@_user.Id">@(!String.IsNullOrEmpty(_user.Name) ? _user.Name : _user.UserName) </a> </h5>
                    <small>Web Developer at Webestica</small>
                    <p class="mt-3">Hi!</p>

                    <!-- User stat START -->
                    <div class="hstack gap-2 gap-xl-3 justify-content-center">
                      <!-- User stat item -->
                      <div>
                        <h6 class="mb-0">@Model.PostCount</h6>
                        <small>Post</small>
                      </div>
                      <!-- Divider -->
                      <div class="vr"></div>
                      <!-- User stat item -->
                      <a asp-area="" asp-controller="Followers" asp-action="Index">
                        <h6 class="mb-0">@Model.FollowerCount</h6>
                        <small>Followers</small>
                      </a>
                      <!-- Divider -->
                      <div class="vr"></div>
                      <!-- User stat item -->
                      <a asp-area="" asp-controller="Following" asp-action="Index">
                        <h6 class="mb-0">@Model.FollowingCount</h6>
                        <small>Following</small>
                      </a>
                    </div>
                    <!-- User stat END -->
                  </div>

                  <!-- Divider -->
                  <hr>
                </div>
                <!-- Card body END -->
                <!-- Card footer -->
                <div class="card-footer text-center py-2">
                  <a class="btn btn-link btn-sm" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@_user.Id">View Profile </a>
                </div>
              </div>
              <!-- Card END -->

              <!-- Copyright -->
              <p class="small text-center mt-1">©2022 <a class="text-body" href="#"> CANBOOKRAM </a></p>
            </div>
          </div>
        </nav>

CANBOOKRAM/Views/Shared/_WhoToFollowPartial.cshtml
@model List<ApplicationUser>

<div class="col-sm-6 col-lg-12">
    <div class="card">
        <!-- Card header START -->
        <div class="card-header pb-0 border-0">
        <h5 class="card-title mb-0">Who to follow</h5>
        </div>
        <!-- Card header END -->
        <!-- Card body START -->
        <div class="card-body">
        @foreach(var item in Model)
        {
            <div class="hstack gap-2 mb-3">
            <!-- Avatar -->
            <a class="avatar" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@item.Id">
                @if (item.ProfilePicture==null)
                {
                    <img class="avatar-img rounded-circle" src="/assets/images/pp.png" alt="">
                }
                else
                {
                        <img class="avatar-img rounded-circle" src="data:image/*;base64,@(Convert.ToBase64String(item.ProfilePicture))" alt="">
                }
            </a>
            <!-- Title -->
            <div class="overflow-hidden">
            <a class="h6 mb-0" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-id="@item.Id">@(!String.IsNullOrEmpty(item.Name) ? item.Name : item.UserName) </a>
            </div>
            <!-- Button -->
            <button class="btn btn-primary-soft rounded-circle icon-md ms-auto" onclick="AddRequest('@item.Id')"><i class="fa-solid fa-plus"> </i></button>
            </div>
        }
           
        <!-- Card body END -->
        </div>
    </div>
</div>

 <script>
function AddRequest(id) {
    $.ajax({
         type: "POST",
         url: "/Home/AddRequest?id=" + id,
         success: function (result) {
             if (result.code == 0) {
                 location.reload();       
             }
             else {
                 alert(result.message); 
             }                    
         },
         error: function (result) {
             alert('An error occured');
         }
     }); 
}
</script>